// let loaderImage = require("../img/loading-spinner-arrow.gif");
// let loaderImage = require('../img/loading-spinner-blue.gif');
let loaderImage = require('../img/new_loader.gif');
export const BREAD_CRUMB_TITLE = 'BREADCRUMBTITLE';
export const SIGN_IN_USER = 'SIGNINUSER';

export const EMPTY='EMPTY';
//Users Constants 
export const GET_USERS = 'GETUSERS';
export const GET_USER_DETAILS = 'GETUSERDETAILS';
export const GET_ROLES = 'GETROLES';

//Settings Constants 
export const GET_INDUSTRIES = 'GETINDUSTRIES';
export const GET_OPPORTUNITY_SOURCE = 'GETOPPORTUNITYSOURCE';
export const GET_ESTIMATE_STAGES = 'GETESTIMATESTAGES';
export const GET_LABOR_RATE_FOR_ADMIN = 'GETLABORRATEFORADMIN';

export const ADD_INDUSTRIES = 'ADDINDUSTRIES';
export const ADD_OPPORTUNITY_SOURCE = 'ADDOPPORTUNITYSOURCE';
export const ADD_LABOR_RATE_FOR_ADMIN = 'ADDLABORRATEFORADMIN';

export const DELETE_INDUSTRIES = 'DELETEINDUSTRIES';
export const DELETE_OPPORTUNITY_SOURCE = 'DELETEOPPORTUNITYSOURCE';
export const DELETE_ORDER_TYPE = 'DELETEORDERTYPE';
export const DELETE_APP_STAGE = 'DELETEAPPSTAGE';
export const DELETE_LABOR_RATE = 'DELETELABORRATE';

//Contact Constants 
export const GET_CONTACTS = 'GETCONTACTS';
export const CREATE_CONTACT = 'CREATECONTACT';
export const UPDATE_CONTACT = 'UPDATECONTACT';
export const GET_CONTACT_DETAILS = 'GETCONTACTDETAILS';
export const GET_CONTACT = 'GETCONTACT';
export const DELETE_CONTACT = 'DELETECONTACT';
export const GET_CONTACT_LINKS = 'GETCONTACTLINKS';
export const ADD_CONTACT_LINKS = 'ADDCONTACTLINKS';
export const REMOVE_CONTACT_LINKS = 'REMOVECONTACTLINKS';
export const GET_CONTACT_LISTS = 'GETCONTACTLISTS';
export const GET_CONTACT_ESTIMATES = 'GETCONTACTESTIMATES';
export const GET_CONTACT_PROPOSALS = 'GETCONTACTPROPOSALS';
export const GET_CONTACT_PROJECTS = 'GETCONTACTPROJECTS';
export const GET_CONTACT_POS = 'GETCONTACTPOS';
export const GET_CONTACT_INVOICES = 'GETCONTACTINVOICES';
export const GET_CONTACT_ACTIVITIES = 'GETCONTACTACTIVITIES';
export const GET_CONTACT_DOCUMENTS = 'GETCONTACTDOCUMENTS';
export const GET_CONTACT_OPPORTUNITIES = 'GETCONTACTOPPORTUNITIES';
export const GET_PARENT_COMPANY_LIST_FOR_CONTACT = 'GETPARENTCOMPANYLISTFORCONTACT';
export const GET_ASSOCIATED_CONTACTS = 'GETASSOCIATEDCONTACTS';
export const ADD_ASSOCIATEDCONTACT = 'ADDASSOCIATEDCONTACT';
export const CONTACT_PIC_PATH = 'CONTACTPICPATH';
export const SALES_SIGN_PATH = 'SALESSIGNPATH';

export const GET_GROUPS = 'GETGROUPS';
export const ADD_GROUP = 'ADDGROUP';
export const DELETE_GROUP = 'DELETEGROUP';
export const GET_MULTIPLE_ADD_CONTACTS = 'GETMULTIPLEADDCONTACTS';
export const GET_MULTIPLE_REMOVE_CONTACTS = 'GETMULTIPLEREMOVECONTACTS';

export const GET_CONTACT_DROPDOWNS = 'GETCONTACTDROPDOWNS';
export const CREATE_CONTACT_MORE = 'CREATECONTACTMORE';
export const ADD_OTHER_TYPE = 'ADDOTHERTYPE';
export const ADD_OTHER_STATUS = 'ADDOTHERSTATUS';
export const ADD_OTHER_SOURCE = 'ADDOTHERSOURCE';
export const ADD_OTHER_DEPARTMENT = 'ADDOTHERDEPARTMENT';
export const DELETE_OTHER_DEPARTMENT = 'DELETEOTHERDEPARTMENT';
export const ADD_OTHER_INDUSTRY = 'ADD_OTHER_INDUSTRY';
export const DELETE_OTHER_INDUSTRY = 'DELETEOTHERINDUSTRY';
export const ADD_OTHER_KEYWORD = 'ADDOTHERKEYWORD';
export const GET_COMPANY_LIST_FOR_CONTACT = 'GETCOMPANYLISTFORCONTACT';
export const GET_DASH_SALESREP = 'GETDASHSALESREP';
export const GET_PROJECT_DROPDOWNS_FOR_DASHBOARD = 'GETPROJECTDROPDOWNSFORDASHBOARD';

export const DASH_TASK_LIST = 'DASHTASKLIST';
export const GET_USERS_FOR_TASK_LIST = 'GET_USERS_FOR_TASK_LIST';
export const DASH_OPPORTUNITIES_LIST = 'DASHOPPORTUNITYLIST';
export const DASH_ESTIMATE_LIST = 'DASHESTIMATELIST';
export const DASH_PROJECTS_LIST = 'DASHPROJECTLIST';
export const DASH_ORDER_LIST = 'DASHORDERLIST';
export const DASH_INVOICE_LIST = 'DASHINVOICELIST';
export const DASH_TAILGATE_LIST = 'DASHTAILGATELIST';
export const DASH_TAILGATE_LIST1 = 'DASHTAILGATELIST1';
export const DASH_GOAL_LIST = 'DASHGOALLIST';


//Opportunity Constants
export const CREATE_OPPORTUNITY = 'CREATEOPPORTUNITY';
export const UPDATE_OPPORTUNITY = 'UPDATEOPPORTUNITY';
export const GET_OPP_CATEGORY = 'GETOPPCATEGORY';
export const ADD_OPP_CATEGORY = 'ADDOPPCATEGORY';
export const GET_COMPANY_LIST = 'GETCOMPANYLIST';
export const GET_END_USER_LIST = 'GETENDUSERLIST';
export const GET_DEPARTMENT_LIST = 'GETDEPARTMENTLIST';
export const GET_INDUSTRY_LIST = 'GETINDUSTRYLIST';
export const ADD_OPP_DEPARTMENT = 'ADD_OPP_DEPARTMENT';
export const ADD_OPP_INDUSTRY = 'ADDOPPINDUSTRY';
export const GET_PHONE_INTERNET = 'GETPHONEINTERNET';
export const GET_OPP_SALESREP = 'GETOPPSALESREP';
export const GET_OPP_INDIVIDUAL = 'GETOPPINDIVIDUAL';
export const GET_OPP_LIST = 'GETOPPLIST';
export const GET_OPP_DETAILVALUES = 'GETOPPDETAILVALUES';
export const GET_OPP_NUMBER = 'GETOPPNUMBER';
export const DELETE_OPPORTUNITY = 'DELETEOPPORTUNITY';
export const GET_OPPS_ESTIMATE = 'GETOPPSESTIMATE';
export const ADD_OTHER_CONTACT = 'ADDOTHERCONTACT';
export const GET_OPPTAGS = 'GETOPPTAGS';
export const GET_OPP_FILES = 'GETOPPFILES';
export const UPLOAD_OPP_FILES = 'UPLOADOPPFILES';
export const UPDATE_FILE_NAME = 'UPDATEFILENAME';
export const DELETE_FILE = 'DELETE_FILE';

//Estimate Constants
export const ESTIMATE_NAME='ESTIMATE_NAME';
export const GET_COMPANY_LIST_FOR_ESTIMATE = 'GETCOMPANYLISTFORESTIMATE';
export const GET_OPPORTUNITY_LIST_FOR_ESTIMATE = 'GETOPPORTUNITYLISTFORESTIMATE';
export const GET_PHONE_INTERNET_FOR_ESTIMATE = 'GETPHONEINTERNETFORESTIMATE';
export const GET_EST_SALESREP = 'GETESTSALESREP';
export const GET_EST_INDIVIDUAL = 'GETESTINDIVIDUAL';
export const GET_ESTIMATE_LIST = 'GETESTIMATELIST';
export const GET_ESTIMATE_DETAILS = 'GETESTIMATEDETAILS';
export const UPDATE_ESTIMATE = 'UPDATEESTIMATE';
export const DELETE_ESTIMATE = 'DELETEESTIMATE';
export const GET_EST_ITEM = 'GETESTITEM';
export const GET_CONTACT_DETAIL_FOR_ESTIMATE = 'GETCONTACTDETAILFORESTIMATE';
export const GET_PROJECT_LIST_FOR_ESTIMATE = 'GETPROJECTLISTFORESTIMATE';
export const GET_PROPOSAL_LIST_FOR_ESTIMATE = 'GETPROPOSALLISTFORESTIMATE';
export const GET_LABOR_RATE = 'GETLABORRATE';
export const ADD_OTHER_SALES = 'ADDOTHERSALES';
export const ADD_OTHER_INDIVIDUAL = 'ADDOTHERINDIVIDUAL';
export const ADD_OTHER_COMPANY = 'ADDOTHERCOMPANY';
export const ADD_OTHER_REVISION = 'ADDOTHERREVISION';
export const GET_ESTIMATE_REVISION = 'GETESTIMATEREVISION';
export const REVISION_LIST_ESTIMATE = 'REVISIONLISTESTIMATE';
export const GET_FORMATS_CONFIGS = 'GETFORMATSCONFIGS';
export const UPDATE_FORMAT_LIST = 'UPDATEFORMATLIST';
export const LOADED_TRUE = 'LOADEDTRUE';
export const UPDATE_OPPORTUNITY_STATE = 'UPDATEOPPORTUNITYSTATE';
export const RENAME_REVISION = 'RENAMEREVISION';
export const DELETE_REVISION = 'DELETEREVISION';
export const GET_ESTIMATE_REVISION_COUNT = 'GETESTIMATEREVISIONCOUNT';
export const CLEAR_SELECTS = 'CLEARSELECTS';
export const ESTIMATE_INLINE_EDIT='ESTIMATE_INLINE_EDIT';
// export const GET_REFRESHED_NAME_ADD = 'GETREFRESHEDNAMEADD';
export const GET_REFRESHED_NAME_UPDATE = 'GETREFRESHEDNAMEUPDATE';
export const GET_ESTIMATE_NUMBER = 'GETESTIMATENUMBER';
export const NEW_ESTIMATE = 'NEWESTIMATE';
export const GET_ESTIMATE_BY_ID='GET_ESTIMATE_BY_ID';
export const GET_COMPANY_EMPLOYEE_LIST='GET_COMPANY_EMPLOYEE_LIST';

//Item Constants
export const GET_ITEM_CATEGORY = 'GETITEMCATEGORY';
export const GET_ITEM_TYPE = 'GETITEMTYPE';
export const ADD_ITEM_CATEGORY = 'ADDITEMCATEGORY';
export const ADD_ITEM_TYPE = 'ADDITEMTYPE';
export const GET_ITEM_LIST = 'GETITEMLIST';
export const GET_ITEM_DETAILVALUES = 'GETITEMDETAILVALUES';
export const DELETE_ITEM = 'DELETEITEM';
export const GET_ITEM_ESTIMATE_LIST = 'GETITEMESTIMATELIST';
export const GET_ITEM_INVOICE_LIST = 'GETITEMINVOICELIST';
export const GET_ITEM_ORDER_LIST = 'GETITEMORDERLIST';
export const GET_RELATED_ITEMS = 'GETITEMITEMS';
export const GET_ALERNATIVE_ITEMS = 'GETALERNATIVEITEMS';
export const GET_REPLACEMENT_ITEMS = 'GETREPLACEMENTITEMS';
export const IMPORT_CSV_DATA = 'IMPORTCSVDATA';
export const GET_ITEM_LOGS = 'GETITEMLOGS';
export const GET_NEW_CREATEITEM = 'GETNEWCREATEITEM';
export const GET_MANUFACTURER_LIST = 'GETMANUFACTURERLIST';
export const MATERIAL_PIC_PATH = 'MATERIALPICPATH';

//Documents constants
export const GET_DOCUMENT_CATEGORY = 'GETDOCUMENTCATEGORY';
export const ADD_DOCUMENT_CATEGORY = 'ADDDOCUMENTCATEGORY';
export const GET_DOC_CLIENT = 'GETDOCCLIENT';
export const GET_DOC_PROJECT = 'GETDOCPROJECT';
export const GET_DOC_ESTIMATE = 'GETDOCESTIMATE';
export const GET_DOC_ORDER = 'GETDOCORDER';
export const GET_DOC_PO = 'GETDOCPO';
export const GET_DOC_OPPORTUNITY = 'GETDOCOPPORTUNITY';
export const GET_DOCUMENT_LIST = 'GETDOCUMENTLIST';
export const GET_DOCUMENT_DETAILVALUES = 'GETDOCUMENTDETAILVALUES';
export const DELETE_DOCUMENT = 'DELETEDOCUMENT';

//Proposals Constants
export const GET_COMPANY_LIST_FOR_PROPOSAL = 'GETCOMPANYLISTFORPROPOSAL';
export const GET_INDIVIDUAL_LIST_FOR_PROPOSAL = 'GETINDIVIDUALLISTFORPROPOSAL';
export const GET_ESTIMATE_LIST_FOR_PROPOSAL = 'GETESTIMATELISTFORPROPOSAL';
export const GET_EMAIL_TEMPLATE = 'GETEMAILTEMPLATE';
export const CREATE_PROPOSAL = 'CREATEPROPOSAL';
export const GET_PHONE_INTERNET_FOR_PROPOSAL = 'GETPHONEINTERNETFORPROPOSAL';
export const GET_PROPOSALS = 'GETPROPOSALS';
export const GET_PROPOSAL_DETAILS = 'GETPROPOSALDETAILS';
export const DELETE_PROPOSAL = 'DELETEPROPOSAL';
export const GET_EMAIL_TEMPLATE_LIST = 'GETEMAILTEMPLATELIST';
export const GET_PROPOSAL_SALESREP='GET_PROPOSAL_SALESREP';
export const GET_PROPOSAL_NUMBER='GET_PROPOSAL_NUMBER';
export const CREATE_PROPOSAL_DATA='CREATE_PROPOSAL_DATA';

//proposal export constants
export const GET_PROPOSAL_FORMATS='GET_PROPOSAL_FORMATS';
export const GET_PROPOSALPDF_DETAILS='GET_PROPOSALPDF_DETAILS';
export const UPDATE_PROPOSAL_FORMAT_LIST='UPDATE_PROPOSAL_FORMAT_LIST';
export const PROPOSAL_LOADED_TRUE='PROPOSAL_LOADED_TRUE';

//Timer Constants
export const GET_TIMER_PROJECT = 'GETTIMERPROJECT';
export const GET_TIMER_CONTACT = 'GETTIMERCONTACT';
export const GET_TIMER_ITEM = 'GETTIMERITEM';
export const GET_TIMER_LIST = 'GETTIMERLIST';
export const GET_TIMER_DETAILVALUES = 'GETTIMERDETAILVALUES';
export const DELETE_TIMER = 'DELETETIMER';

//Project Constants
export const GET_PROJECT_DROPDOWNS = 'GETPROJECTDROPDOWNS';
export const GET_COMPANY_LIST_FOR_PROJECT = 'GETCOMPANYLISTFORPROJECT';
export const GET_INDIVIDUAL_LIST_FOR_PROJECT = 'GETINDIVIDUALLISTFORPROJECT';
export const ADD_OTHER_DEPARTMENT_FOR_PROJECT = 'ADDOTHERDEPARTMENTFORPROJECT';
export const ADD_OTHER_CATEGORY_FOR_PROJECT = 'ADDOTHERCATEGORYFORPROJECT';
export const GET_PROJECTS_LIST = 'GETPROJECTSLIST';
export const DELETE_PROJECT = 'DELETEPROJECT';
export const GET_PROJECT_DETAILS = 'GETPROJECTDETAILS';

//Project More Options
export const GET_TRACKING_ITEM = 'GETTRACKINGITEM';
export const GET_COSTING_DATA = 'GETCOSTINGDATA';
export const GET_PROJECT_ACTIVITY = 'GETPROJECTACTIVITY';
export const GET_PROJECT_TIMER = 'GETPROJECTTIMER';
export const GET_PROJECT_DOCUMENT = 'GETPROJECTDOCUMENT';
export const GET_PROJECT_INVOICE = 'GETPROJECTINVOICE';
export const GET_PROJECT_DAILIES = 'GETPROJECTDAILIES';
export const GET_PROJECT_TOOLS = 'GETPROJECTTOOLS';
export const GET_PROJECT_ESTIMATE = 'GETPROJECTESTIMATE';
export const ADD_DAILY_REPORT = 'ADDDAILYREPORT';
export const DELETE_DAILY_REPORT = 'DELETEDAILYREPORT';
export const GET_PROJECT_PO = 'GETPROJECTPO';
export const GET_PROJECT_EXPENSES = 'GETPROJECTEXPENSES';

//activity Options
export const GET_ACTIVITY_LIST = 'GETACTIVITYLIST';
export const DELETE_ACTIVITY = 'DELETEACTIVITY';
export const GET_ACTIVITY_TEMPLATE = 'GETACTIVITYTEMPLATE';
export const GET_ACTIVITY_CATEGORY = 'GETACTIVITYCATEGORY';
export const GET_ACTIVITY_DETAILS = 'GETACTIVITYDETAILS';

//Calendar Constants
export const GET_EVENT_RECORD_LIST = 'GETEVENTRECORDLIST';
export const GET_INDIVIDUALS_LISTS = 'GETINDIVIDUALSLISTS';
export const EVENT_LIST_BY_CONTACT = 'EVENTLISTBYCONTACT';

//PO Constants
export const GET_REQUESTBY = 'GETREQUESTBY';
export const GET_PO_LIST = 'GETPOLIST';
export const DELETE_PO = 'DELETEPO';
export const GET_PO_DETAILS = 'GETPODETAILS';
export const UPDATE_ATTACHMENT = 'UPDATEATTACHMENT';
export const DELETE_ATTACHMENT = 'DELETEATTACHMENT';
export const GET_PO_ITEM = 'GETPOITEM';
export const GET_LABOR_RATE_PO = 'GETLABORRATEPO';
export const GET_PO_NO='GET_PO_NO';

//Service Orders Constants
export const GET_ORDER_LIST = 'GETORDERLIST';
export const DELETE_ORDER = 'DELETEORDER';
export const GET_ORDER_DETAILS = 'GETORDERDETAILS';
export const ADD_OTHER_ORDER_TYPE = 'ADDOTHERORDERTYPE';
export const GET_OTHER_ORDER_TYPE = 'GETOTHERORDERTYPE';
export const GET_BILLING_COMPANIES = 'GETBILLINGCOMPANIES';
export const GET_ORDER_ITEM = 'GETORDERITEM';
export const GET_LABOR_RATE_ORDER = 'GETLABORRATEORDER';
export const GET_COMPANY_LIST_ORDER = 'GETCOMPANYLISTORDER';
export const GET_ORDER_NO = 'GETORDERNO';
export const GET_ORDER_CONTRACT = 'GETORDERCONTRACT';
export const ADD_ORDER_CONTRACT = 'ADDORDERCONTRACT';

//Expenses Constants
export const GET_PROJECT_LIST_FOR_EXPENSE = 'GETPROJECTLISTFOREXPENSE';
export const GET_EXPENSES_LIST = 'GETEXPENSESLIST';
export const GET_EXPENSE_DETAILS = 'GETEXPENSEDETAILS';

//Invoice Constants
export const GET_INVOICE_LIST = 'GETINVOICELIST';
export const DELETE_INVOICE = 'DELETEINVOICE';
export const GET_INVOICE_DETAILS = 'GETINVOICEDETAILS';
//account constants
export const ACCOUNT_TITLE='ACCOUNT_TITLE';
export const INVITE_USER='INVITE_USER';
export const GET_ACCOUNT_USERS='GET_ACCOUNT_USERS';
export const RESEND_INVITATION='RESEND_INVITATION';
export const UPDATE_USER_STATUS='UPDATE_USER_STATUS';
export const DELETE_USER='DELETE_USER';
export const COMPANY_USER_DETAILS='COMPANY_USER_DETAILS';
export const RESET_USER_PASSWORD='RESET_USER_PASSWORD';
export const UPDATE_COMPANY_USER_PROFILE='UPDATE_COMPANY_USER_PROFILE';
export const UPDATE_COMPANY_PIC='UPDATE_COMPANY_PIC';
export const USER_DETAILS='USER_DETAILS';
export const CHECK_IS_ACCEPTED='CHECK_IS_ACCEPTED';
export const SET_COMPANY_USERS_PASSWORD='SET_COMPANY_USERS_PASSWORD';
export const GET_COMPANY_USER_ACTIVITY='GET_COMPANY_USER_ACTIVITY';
export const ADD_USER_ACTIVITY='ADD_USER_ACTIVITY';
export const GET_USER_ACTIVITY='GET_USER_ACTIVITY';

//Loader Image

//Work Log
export const GET_PROJECT_AND_SO='GET_PROJECT_AND_SO';
export const CREATE_WORKLOG='CREATE_WORKLOG';
export const GET_WORKLOG_LIST='GET_WORKLOG_LIST';
export const GET_WORKLOG_DETAIL='GET_WORKLOG_DETAIL';
export const ADD_OTHER='ADD_OTHER';
export const WORKLOG_NO='WORKLOG_NO';
export const WORKLOG_ADD_OTHER='WORKLOG_ADD_OTHER';

// export const GET_LOADER_IMAGE = '<img src="../img/new_loader.gif"/>';
export const GET_LOADER_IMAGE = '<img src='+loaderImage+'>';//previous loader

// export const EXPORT_LOADER_IMAGE = '<h5>'+'<img src='+loaderImage+'> Exporting PDF...</h5>';

// export const GET_LOADER_IMAGE = '<h5>'+'<img src="../img/loading-spinner-blue.gif">  Loading...</h5>';//previous loader
// export const GET_LOADER_IMAGE = '<h5><img src="../img/loading-spinner-blue.gif"> Processing...</h5>';
// export const EXPORT_LOADER_IMAGE = '<h5>'+'<img src="../img/loading-spinner-blue.gif"> Exporting PDF...</h5>';
// export const GET_UPLOADING = '<h5><img src="https://elsevierafrica.com/public/assets/style/img/loading-spinner-blue.gif"> Uploading File...</h5>';
// export const GET_IMPORTING = '<h5><img src="https://elsevierafrica.com/public/assets/style/img/loading-spinner-blue.gif"> Importing Items...</h5>';
// export const GET_LOADER_IMAGE = "http://elsevierafrica.com/public/assets/style/img/loading-spinner-blue.gif ";
// export const GET_LOADER_TEXT = " Processing...";

export const COMPANY_EXISTANCE = 'Company does not exist, please select company from list.';

