export default {
  contactDropdowns: {
    Department: [],
    contact: [],
    industry: [],
    source: [],
    status: [],
    type: [],
    group: [],
    keyword: []
  },
  contactList: {
    contact: [],
    totalcount: 0,
    sortColumnName: null,
    sortOrder: null,
    page: 1,
    per_page: 0
  },
  contactDetails: [],
  groupData: [],
  multipleAddContacts: [],
  contactLinkData: [],
  contactListsData: [],
  contactEstimatesData: [],
  contactProposalsData: [],
  contactProjectsData: [],
  contactPosData: [],
  contactInvoicesData: [],
  contactActivitiesData: [],
  contactDocumentsData: [],
  contactOpportunitiesData: [],
  companyList: [],
  parentCompanyList: [],
  associatedContacts: [],
  contactData: {
    departmentInfo: [],
    industryInfo: [],
    referredByInfo: [],
    typeInfo: [],
    statusInfo: [],
    sourcesInfo: [],
    phoneInfo: [],
    internetInfo: [],
    addressInfo: []
  },
  individualAssociated: '',
  imagePath: '',
  salesImagePath: ''
};
